name: un_jour_un_mot
description: "Un jour un mot - FLE"

publish_to: 'none'

version: 2.0.0+14

environment:
  sdk: ^3.7.0-257.0.dev

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  bottom_navy_bar: ^6.1.0
  provider: ^6.1.5
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  flashy_flushbar: ^1.4.0
  google_sign_in: ^6.3.0
  firebase_auth: ^5.6.0
  confirm_dialog: ^1.0.4
  in_app_purchase: ^3.2.3
  dots_indicator: ^4.0.1
  shared_preferences: ^2.5.3
  introduction_screen: ^3.1.17
  google_mobile_ads: ^6.0.0
  universal_html: ^2.2.4
  http: ^1.4.0
  dio: ^5.8.0+1
  firebase_messaging: ^15.2.10
  flutter_paypal_payment: ^1.0.8
  url_launcher: ^6.3.2
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/pendu/
    - assets/on_boarding/
